[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.8"
nalgebra = { version = "0.33.0", features = ["serde", "serde-serialize"] }
serde = "1.0.203"
serde_json = "1.0.117"
