[package]
name = "visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.16.1"
pollster = "0.3.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
wgpu = "0.20.1"
winit = "0.29"
